# Generated by Django 3.2 on 2021-04-25 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(verbose_name='Category Slug')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Contact No.')),
                ('subject', models.CharField(max_length=40, verbose_name='Subject')),
                ('message', models.TextField(max_length=300, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Contact Date')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sub Category Name')),
                ('slug', models.SlugField(verbose_name='Sub Category Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MsBlog.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('slug', models.SlugField(verbose_name='Post Slug')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Post Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Product Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Product Image Thumbnail')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Product Added Date')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='MsBlog.subcategory')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Comment On Post')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='MsBlog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
