# Generated by Django 3.2 on 2021-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date'], 'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-date'], 'verbose_name': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added'], 'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Sub Category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Category Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Post Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sub Category Slug'),
        ),
    ]
