# Generated by Django 3.2 on 2021-04-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
