# Generated by Django 3.2 on 2021-04-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0010_alter_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
    ]
