# Generated by Django 3.2 on 2021-04-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0012_alter_comments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postComment', to='MsBlog.post'),
        ),
    ]
