# Generated by Django 3.2 on 2021-04-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0013_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
