# Generated by Django 3.2 on 2021-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0014_rename_user_id_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Sub Category Image'),
        ),
    ]
