# Generated by Django 3.2 on 2021-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MsBlog', '0017_alter_contactus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Comment Date'),
        ),
    ]
